services:
    _defaults:
        public: false

    Kira0269\LogViewerBundle\Controller\:
        resource: '../../Controller/'
        autoconfigure: true
        autowire: true

    Kira0269\LogViewerBundle\LogParser\LogParserInterface:
        class: Kira0269\LogViewerBundle\LogParser\LogParser

    kira_log_viewer.log_parser.default:
        alias: 'Kira0269\LogViewerBundle\LogParser\LogParserInterface'
        public: true
